### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by mhwebuz** [Itz-fork/Nexa-Userbot#17]
Jan 27 09:45:34 PM  ==> Starting service with 'python -m nexa_userbot'
Jan 27 09:45:39 PM  Traceback (most recent call last):
Jan 27 09:45:39 PM    File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
Jan 27 09:45:39 PM      mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
Jan 27 09:45:39 PM    File "/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
Jan 27 09:45:39 PM      return _get_module_details(pkg_main_name, error)
Jan 27 09:45:39 PM    File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
Jan 27 09:45:39 PM      __import__(pkg_name)
Jan 27 09:45:39 PM    File "/opt/render/project/src/nexa_userbot/__init__.py", line 15, in <module>
Jan 27 09:45:39 PM      sleep_threshold=10
Jan 27 09:45:39 PM  TypeError: __init__() got an unexpected keyword argument 'session_name'

Why?

**Comment by vash206** [comment]
Its was control mee

**Comment by vash206** [comment]
> Jan 27 09:45:34 PM ==> Starting service with 'python -m nexa_userbot' Jan 27 09:45:39 PM Traceback (most recent call last): Jan 27 09:45:39 PM File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main Jan 27 09:45:39 PM mod_name, mod_spec, code = _get_module_details(mod_name, _Error) Jan 27 09:45:39 PM File "/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details Jan 27 09:45:39 PM return _get_module_details(pkg_main_name, error) Jan 27 09:45:39 PM File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details Jan 27 09:45:39 PM **import**(pkg_name) Jan 27 09:45:39 PM File "/opt/render/project/src/nexa_userbot/**init**.py", line 15, in Jan 27 09:45:39 PM sleep_threshold=10 Jan 27 09:45:39 PM TypeError: **init**(cirek
) got an unexpected keyword argument 'session_name'
> 
> Why?
